export const EDITOR_CONTENT_HORIZONTAL_PADDING_PX = 12;

export const LINE_NUMBER_GUTTER_CONTENT_WIDTH = '6ch';
export const LINE_NUMBER_GUTTER_PADDING_RIGHT = '2ch';
export const LINE_NUMBER_GUTTER_TOTAL_WIDTH = `calc(${LINE_NUMBER_GUTTER_CONTENT_WIDTH} + ${LINE_NUMBER_GUTTER_PADDING_RIGHT})`;

export const LEFT_LINE_NUMBER_TEXT_NUDGE = '0ch';
export const RIGHT_LINE_NUMBER_TEXT_NUDGE = '-0.75ch';

export const LEFT_RESIZE_HANDLE_NUDGE_PX = 0;
export const RIGHT_RESIZE_HANDLE_NUDGE_PX = 4;

export const FULL_LINE_HIGHLIGHT_LEFT_NUDGE_PX = 0;
export const FULL_LINE_HIGHLIGHT_RIGHT_NUDGE_PX = 0;

export const FONT_SIZE_ICON_SMALL_T_CLASS_NAME = 'text-[0.76em] font-bold';
